wandb_version: 1

emb_dim:
  desc: null
  value: 128
hid_dim:
  desc: null
  value: 256
n_layers:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 64
lr:
  desc: null
  value: 0.001
_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.16.6
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1748408810.0
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 105
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 105
      3:
      - 13
      - 16
      - 23
      4: 3.8.19
      5: 0.16.6
      8:
      - 3
      - 5
      13: windows-amd64
